-- Phase 2 thin migration: users + appointments (includes status: requested)
-- Run against FREEPDB1 as SYSTEM (or app user with DDL rights):
--   docker exec -i oracle-medicus-ops sqlplus -s system/${ORACLE_PWD}@FREEPDB1 @/path/to/001_phase2_public.sql

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    email VARCHAR2(320) NOT NULL,
    password_hash VARCHAR2(255),
    specialty VARCHAR2(100),
    phone VARCHAR2(20),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    patient_name VARCHAR2(200) NOT NULL,
    patient_phone VARCHAR2(20) NOT NULL,
    patient_email VARCHAR2(320),
    scheduled_at TIMESTAMP,
    duration_minutes NUMBER DEFAULT 30 NOT NULL,
    status VARCHAR2(20) DEFAULT ''requested'' NOT NULL,
    notes VARCHAR2(4000),
    reminder_sent NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_appointments_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_appointment_status CHECK (
      status IN (''requested'', ''scheduled'', ''completed'', ''cancelled'', ''no_show'')
    )
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM users WHERE email = 'doctor@medicus-ops.local';
  IF v_count = 0 THEN
    INSERT INTO users (name, email, specialty, phone)
    VALUES (
      'Dr. Abhinav Gade',
      'doctor@medicus-ops.local',
      'Urology',
      '+919876543210'
    );
  END IF;
END;
/

COMMIT;
